### ISSUE TITLE
Read/write mutex

### ISSUE THREAD

**Issue by hoylen** [mezoni/locking#5]
I want to add support for a read/write mutex. That is, one that can be _acquired_ for either reading or writing. Multiple reads can be simultaneously acquired, but only a single write can be acquired at any one time. Reads and writes cannot be simultaneously acquired.

What is the best way to implement this? Looking at the current design, I'm thinking that the `acquire` method's signature could change to accept an optional "lock type" parameter (write or read), but it will be an error to pass in "read" for the _NormalMutex_ and _ReentrantMutex_. Alternatively, _acquireRead_ and _acquireWrite_ methods could be defined, but that could mess up the current extends/implements hierarchy.

What do you think?

**Comment by mezoni** [comment]
I am sorry but this software is obsolete.
You can use it as you wish (modify, distribute) without any mentions about the original author(s).
P.S.
This software (https://github.com/mezoni/semaphore) was used in a real project.

**Comment by hoylen** [comment]
Ok.

I looked around and thought _locking_ was the most mature of the available mutex packages :-) Unfortunately, semaphores by themselves are not sufficient for my needs.

Is there anyway you can mark the _locking_ package as obsolete, so others aren't tempted to use it? Minimally putting a warning message at the top of the README and publishing a new release?

Thanks.

**Comment by mezoni** [comment]
[Semaphores vs. mutexes](https://en.wikipedia.org/wiki/Semaphore_(programming)#Semaphores_vs._mutexes)

Semaphores vs. mutexes
A mutex is essentially the same thing as a binary semaphore and sometimes uses the same basic implementation. The differences between them are in how they are used. While a binary semaphore may be used as a mutex, a mutex is a more specific use-case, in that only the thread that locked the mutex is supposed to unlock it.

In Dart implementation a single isolate uses a single thread, this means that  in Dart "soft" murex is the same as a binary semaphore. 

Semaphores which allow an arbitrary resource count are called counting semaphores, while semaphores which are restricted to the values 0 and 1 (or locked/unlocked, unavailable/available) are called binary semaphores and are used to implement locks.

That is counting semaphores which are restricted to the values 0 and 1 is the same as binary semaphores.

So, you can implement you own mutex on top of the semaphore.
In the same way you can implement your own kind of mutex (eg. read/write mutex).

P.S.

This software (https://github.com/mezoni/threading) was an attempt to implement a more specific (based on Dart Zones) simulation of the "soft" threads and sinchronisation.
But it was abandoned and it not completed.

**Comment by hoylen** [comment]
Yes, I came across the [threading](https://pub.dartlang.org/packages/threading) package on [pub.dartlang.org](https://pub.dartlang.org) too :-)

**Comment by mezoni** [comment]
This software (https://github.com/mezoni/threading) was very interesting project (at least, for me) but interest of Dart Team was limited to that the Dart should be sucessfully used with Angular and this is more than enough.
Trying to negotiate about something with the Dart Team is simply impossible.

Even if I find a flaw in the implementation (eg. Zones API) and propose improvements, they will still respond to me - "This covers a very narrow range of interests."

Or speaking another language this might sound so - "How these improvements can improve interaction with Angular frameworks?".

In general, I am no longer working with Dart.

P.S.
I am trying to implement these project only because a package manager "pub" is very limited in features and does not provides way to install third party software (eg. native extensions with supplied binary or compilable software).

**Comment by hoylen** [comment]
I'm using Dart on the server side, where protecting multi-step operations is important when processing multiple simultaneous requests that might want to access the same resource.

Someone with a focus on client side Dart would think such things are a "very narrow range of interest" because it is outside their client side focus :-(

**Comment by mezoni** [comment]
You have correctly understood everything. So you should not count on my help.
Ask Dart Team members, maybe they can help you (use Dart on the server side).
